# Generated by Django 5.2.6 on 2025-09-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='reps',
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
