# Generated by Django 5.2.6 on 2025-09-06 22:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_set_reps'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='entrydate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='set',
            name='reps',
            field=models.IntegerField(default=0),
        ),
    ]
